---
title: Scivolare verso un oggetto e tornare indietro
hero_image: images/banner.png
description: Scivolare verso un oggetto e tornare indietro
version: 4
listed: false
copyedit: false
last_tested: "2021-05-13"
steps:
  - title: Scivolare verso un oggetto e tornare indietro
